// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200831154323_dataFillUpdate")]
    partial class dataFillUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("caseSize")
                        .HasColumnType("INTEGER");

                    b.Property<double>("cost")
                        .HasColumnType("REAL");

                    b.Property<double>("expectedFloor")
                        .HasColumnType("REAL");

                    b.Property<double>("expectedInv")
                        .HasColumnType("REAL");

                    b.Property<double>("fill")
                        .HasColumnType("REAL");

                    b.Property<double>("netGIG")
                        .HasColumnType("REAL");

                    b.Property<bool>("onSale")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("organic")
                        .HasColumnType("INTEGER");

                    b.Property<double>("par")
                        .HasColumnType("REAL");

                    b.Property<double>("percentSales")
                        .HasColumnType("REAL");

                    b.Property<bool>("productActive")
                        .HasColumnType("INTEGER");

                    b.Property<double>("retailPrice")
                        .HasColumnType("REAL");

                    b.Property<double>("shrink")
                        .HasColumnType("REAL");

                    b.Property<double>("sold")
                        .HasColumnType("REAL");

                    b.Property<string>("soldBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
