// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210320153913_addingVINcolumn")]
    partial class addingVINcolumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("caseSize")
                        .HasColumnType("int");

                    b.Property<double>("cost")
                        .HasColumnType("float");

                    b.Property<double>("expectedFloor")
                        .HasColumnType("float");

                    b.Property<double>("expectedInv")
                        .HasColumnType("float");

                    b.Property<double>("fill")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("netGIG")
                        .HasColumnType("float");

                    b.Property<bool>("onSale")
                        .HasColumnType("bit");

                    b.Property<bool>("organic")
                        .HasColumnType("bit");

                    b.Property<double>("par")
                        .HasColumnType("float");

                    b.Property<double>("percentSales")
                        .HasColumnType("float");

                    b.Property<bool>("productActive")
                        .HasColumnType("bit");

                    b.Property<double>("retailPrice")
                        .HasColumnType("float");

                    b.Property<double>("shrink")
                        .HasColumnType("float");

                    b.Property<double>("sold")
                        .HasColumnType("float");

                    b.Property<string>("soldBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("vin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
